[editor]
# Editor minimum width (>= 800)
width = 1000
# Editor minimum height (>= 600)
height = 800
# Gonvim copy the yank text to clipboad
clipboard = true
# Editor font-family, font-size, linespace.
#  Note: If you want to control the font, linespace with the neovim command, you need 'equalsraf/neovim-gui-shim'.
fontFamily = "Fira Code Retina"
fontsize = 10
linespace = 10
# Editor cursor blink
cursorBlink = false
# Disable IME in Normal mode
disableIMEinNormal = true

[statusLine]
# textLabel / icon / background / none, default is "textLabel"
modeIndicatorType = "background"
# color for textLabel / background color for mode indicator
normalModeColor = "#123456"
commandModeColor = "#123456"
insertModeColor = "#123456"
replaceModeColor = "#123456"
visualModeColor = "#123456"
termnalModeColor = "#123456"

[miniMap]
visible = false

[scrollBar]
visible = true

[activityBar]
visible = true
dropshadow = false

[sideBar]
visible = false
dropshadow = false
width = 300
accentColor = "#519aba"

[workspace]
# name: directoryname
# full: /path/to/directoryname
# minimum: /p/t/directoryname
pathStyle = "full"
# Restore session-information that was ended without being saved
restoreSession = false
